spring.application.name=MusiFlow-Backend
spring.cloud.config.enabled=false
spring.autoconfigure.exclude=org.springframework.ai.autoconfigure.vectorstore.mongo.MongoDBAtlasVectorStoreAutoConfiguration

spring.data.mongodb.database=mp3Database
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017

spring.data.mongodb.username=usuari
spring.data.mongodb.password=MongoDB

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

cloudflare.r2.accessKeyId=2a9bf7d46353327fc03407c5be82ac64
cloudflare.r2.secretAccessKey=f5c279e203602dc5087bba848c4695d7ae82b0a0180cd1e94401a9efe1c5bf58
cloudflare.r2.endpoint=https://0983b125c60ed4c87ecebc29f9dbccdc.r2.cloudflarestorage.com
cloudflare.r2.bucketName=musicflow
